[browser]
gatherUsageStats = true

[server]
maxUploadSize = 50

[theme]
base="light"
primaryColor="#F63310"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"